# Generated by Django 5.0.2 on 2024-02-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CifUserDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cif_id', models.CharField(max_length=100, unique=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('profile_type', models.CharField(max_length=20)),
                ('user_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField(unique=True)),
                ('version', models.SmallIntegerField(unique=True)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
